{-# LANGUAGE LambdaCase #-}

-- | The three block sets of the original game and piece spawning.
module Blockout.Pieces
    ( Proto
    , protosOf
    , spawnable
    , spawnCells
    , extendedSet
    ) where

import Data.List (nub, sort, sortOn)
import Data.Maybe (mapMaybe)
import qualified Data.Set as Set

import Blockout.Types

-- | A piece shape: cube offsets with the bounding box corner at the origin.
type Proto = [Cell]

protosOf :: BlockSet -> [Proto]
protosOf = \case
    Flat -> flatSet
    Basic -> basicSet
    Extended -> extendedSet

{- | The FLAT set (manual blocks 1, 2, 5, 6, 9, 10, 13, 14): the eight
planar pieces of 1 to 4 cubes used by the original. Note there is no
1x4 bar, faithful to the original.
-}
flatSet :: [Proto]
flatSet =
    map
        (map (\(x, y) -> (x, y, 0)))
        [ [(0, 0)] -- single cube
        , [(0, 0), (1, 0)] -- domino
        , [(0, 0), (1, 0), (2, 0)] -- 1x3
        , [(0, 0), (1, 0), (0, 1)] -- corner (V)
        , [(0, 0), (1, 0), (0, 1), (1, 1)] -- 2x2 square
        , [(0, 0), (1, 0), (2, 0), (0, 1)] -- L
        , [(0, 0), (1, 0), (2, 0), (1, 1)] -- T
        , [(1, 0), (2, 0), (0, 1), (1, 1)] -- S
        ]

{- | The BASIC set (manual blocks 1-7): the seven Soma pieces, which
together contain 27 cubes and assemble into a 3x3x3 cube.
-}
basicSet :: [Proto]
basicSet =
    [ [(0, 0, 0), (1, 0, 0), (0, 1, 0)] -- V
    , [(0, 0, 0), (1, 0, 0), (2, 0, 0), (0, 1, 0)] -- L
    , [(0, 0, 0), (1, 0, 0), (2, 0, 0), (1, 1, 0)] -- T
    , [(1, 0, 0), (2, 0, 0), (0, 1, 0), (1, 1, 0)] -- Z
    , [(0, 0, 0), (1, 0, 0), (1, 1, 0), (1, 1, 1)] -- left screw
    , [(0, 0, 1), (1, 0, 1), (1, 1, 1), (1, 1, 0)] -- right screw
    , [(0, 0, 0), (1, 0, 0), (0, 1, 0), (0, 0, 1)] -- branch
    ]

{- | The EXTENDED set (manual blocks 1-41): all polycubes of 1 to 5 cubes,
distinct up to rotation (mirror images count as different blocks, as
with real hardwood pieces). Sizes 1+1+2+8+29 give the manual's 41.
-}
extendedSet :: [Proto]
extendedSet = concatMap polycubes [1 .. 5]

polycubes :: Int -> [Proto]
polycubes 1 = [[(0, 0, 0)]]
polycubes n =
    Set.toList . Set.fromList $
        [ canon (c : p)
        | p <- polycubes (n - 1)
        , c <- nub [nb | cell <- p, nb <- neighbors cell]
        , c `notElem` p
        ]
  where
    neighbors (x, y, z) =
        [ (x - 1, y, z)
        , (x + 1, y, z)
        , (x, y - 1, z)
        , (x, y + 1, z)
        , (x, y, z - 1)
        , (x, y, z + 1)
        ]

-- | Canonical representative of a shape under the 24 proper rotations.
canon :: Proto -> Proto
canon p = minimum [normalize (map (applyM r) p) | r <- rotations]

-- | Translate the bounding box corner to the origin and sort the cells.
normalize :: Proto -> Proto
normalize cs =
    sort [(x - mx, y - my, z - mz) | (x, y, z) <- cs]
  where
    mx = minimum [x | (x, _, _) <- cs]
    my = minimum [y | (_, y, _) <- cs]
    mz = minimum [z | (_, _, z) <- cs]

-- | A rotation matrix as the images of the three basis vectors.
type Mat = (Cell, Cell, Cell)

applyM :: Mat -> Cell -> Cell
applyM ((a1, a2, a3), (b1, b2, b3), (c1, c2, c3)) (x, y, z) =
    ( x * a1 + y * b1 + z * c1
    , x * a2 + y * b2 + z * c2
    , x * a3 + y * b3 + z * c3
    )

-- | All 24 proper rotations, generated by 90 degree X and Z turns.
rotations :: [Mat]
rotations = Set.toList (go (Set.singleton identity))
  where
    identity = ((1, 0, 0), (0, 1, 0), (0, 0, 1))
    rx = ((1, 0, 0), (0, 0, 1), (0, -1, 0))
    rz = ((0, 1, 0), (-1, 0, 0), (0, 0, 1))
    go s
        | Set.size s' == Set.size s = s
        | otherwise = go s'
      where
        s' =
            Set.union s $
                Set.fromList
                    [compose g m | m <- Set.toList s, g <- [rx, rz]]
    compose g (e1, e2, e3) = (applyM g e1, applyM g e2, applyM g e3)

extent :: Proto -> (Int, Int, Int)
extent cs =
    ( maximum [x | (x, _, _) <- cs] + 1
    , maximum [y | (_, y, _) <- cs] + 1
    , maximum [z | (_, _, z) <- cs] + 1
    )

{- | The pieces of the setup's block set that fit the pit, each in its
flattest spawn orientation. Pieces too big for the pit are never
generated (manual note on the Extended set).
-}
spawnable :: Setup -> [Proto]
spawnable s = mapMaybe best (protosOf (setupSet s))
  where
    best p = case sortOn measure (filter fitsPit orientations) of
        (q : _) -> Just q
        [] -> Nothing
      where
        orientations = nub [normalize (map (applyM r) p) | r <- rotations]
    fitsPit q =
        let (dx, dy, dz) = extent q
         in dx <= setupW s && dy <= setupL s && dz <= setupD s
    measure q = let (dx, dy, dz) = extent q in (dz, dy, dx)

-- | Place a piece centered at the mouth of the pit.
spawnCells :: Setup -> Proto -> [Cell]
spawnCells s ps = [(x + ox, y + oy, z) | (x, y, z) <- ps]
  where
    (dx, dy, _) = extent ps
    ox = (setupW s - dx) `div` 2
    oy = (setupL s - dy) `div` 2
